CREATE TABLE countries (
	ID SMALLINT( 3 ) NOT NULL AUTO_INCREMENT,
	country VARCHAR( 100 ) NOT NULL ,
	PRIMARY KEY ( ID )
);
insert into countries (country) values ('Albania');
insert into countries (country) values ('Algeria');
insert into countries (country) values ('Andorra');
insert into countries (country) values ('Angola');
insert into countries (country) values ('Anguilla');
insert into countries (country) values ('Antarctica');
insert into countries (country) values ('Antigua');
insert into countries (country) values ('Antilles');
insert into countries (country) values ('Argentina');
insert into countries (country) values ('Armenia');
insert into countries (country) values ('Aruba');
insert into countries (country) values ('Australia');
insert into countries (country) values ('Austria');
insert into countries (country) values ('Azerbaijan');
insert into countries (country) values ('Bahamas');
insert into countries (country) values ('Bangladesh');
insert into countries (country) values ('Barbados');
insert into countries (country) values ('Belarus');
insert into countries (country) values ('Belgium');
insert into countries (country) values ('Belize');
insert into countries (country) values ('Benin');
insert into countries (country) values ('Bermuda');
insert into countries (country) values ('Bhutan');
insert into countries (country) values ('Bolivia');
insert into countries (country) values ('Bosnia');
insert into countries (country) values ('Botswana');
insert into countries (country) values ('Brazil');
insert into countries (country) values ('Brunei');
insert into countries (country) values ('Bulgaria');
insert into countries (country) values ('Burkina Faso');
insert into countries (country) values ('Burundi');
insert into countries (country) values ('Cambodia');
insert into countries (country) values ('Cameroon');
insert into countries (country) values ('Canada');
insert into countries (country) values ('Cape Verde');
insert into countries (country) values ('Cayman Islands');
insert into countries (country) values ('Central Africa');
insert into countries (country) values ('Chad');
insert into countries (country) values ('Chile');
insert into countries (country) values ('China');
insert into countries (country) values ('Colombia');
insert into countries (country) values ('Comoros');
insert into countries (country) values ('Congo');
insert into countries (country) values ('Cook Islands');
insert into countries (country) values ('Costa Rica');
insert into countries (country) values ('Cote D''Ivoire');
insert into countries (country) values ('Croatia');
insert into countries (country) values ('Cuba');
insert into countries (country) values ('Cyprus');
insert into countries (country) values ('Czech Republic');
insert into countries (country) values ('Denmark');
insert into countries (country) values ('Djibouti');
insert into countries (country) values ('Dominica');
insert into countries (country) values ('Dominican Rep.');
insert into countries (country) values ('Ecuador');
insert into countries (country) values ('Egypt');
insert into countries (country) values ('El Salvador');
insert into countries (country) values ('Eritrea');
insert into countries (country) values ('Estonia');
insert into countries (country) values ('Ethiopia');
insert into countries (country) values ('Fiji');
insert into countries (country) values ('Finland');
insert into countries (country) values ('Falkland Islands');
insert into countries (country) values ('France');
insert into countries (country) values ('Gabon');
insert into countries (country) values ('Gambia');
insert into countries (country) values ('Georgia');
insert into countries (country) values ('Germany');
insert into countries (country) values ('Ghana');
insert into countries (country) values ('Gibraltar');
insert into countries (country) values ('Greece');
insert into countries (country) values ('Greenland');
insert into countries (country) values ('Grenada');
insert into countries (country) values ('Guam');
insert into countries (country) values ('Guatemala');
insert into countries (country) values ('Guiana');
insert into countries (country) values ('Guinea');
insert into countries (country) values ('Guyana');
insert into countries (country) values ('Haiti');
insert into countries (country) values ('Hondoras');
insert into countries (country) values ('Hong Kong');
insert into countries (country) values ('Hungary');
insert into countries (country) values ('Iceland');
insert into countries (country) values ('India');
insert into countries (country) values ('Indonesia');
insert into countries (country) values ('Iran');
insert into countries (country) values ('Iraq');
insert into countries (country) values ('Ireland');
insert into countries (country) values ('Israel');
insert into countries (country) values ('Italy');
insert into countries (country) values ('Jamaica');
insert into countries (country) values ('Japan');
insert into countries (country) values ('Jordan');
insert into countries (country) values ('Kazakhstan');
insert into countries (country) values ('Kenya');
insert into countries (country) values ('Kiribati');
insert into countries (country) values ('Korea');
insert into countries (country) values ('Kyrgyzstan');
insert into countries (country) values ('Lao');
insert into countries (country) values ('Latvia');
insert into countries (country) values ('Lesotho');
insert into countries (country) values ('Liberia');
insert into countries (country) values ('Liechtenstein');
insert into countries (country) values ('Lithuania');
insert into countries (country) values ('Luxembourg');
insert into countries (country) values ('Macau');
insert into countries (country) values ('Macedonia');
insert into countries (country) values ('Madagascar');
insert into countries (country) values ('Malawi');
insert into countries (country) values ('Malaysia');
insert into countries (country) values ('Maldives');
insert into countries (country) values ('Mali');
insert into countries (country) values ('Malta');
insert into countries (country) values ('Marshal Islands');
insert into countries (country) values ('Martinique');
insert into countries (country) values ('Mauritania');
insert into countries (country) values ('Mauritius');
insert into countries (country) values ('Mayotte');
insert into countries (country) values ('Mexico');
insert into countries (country) values ('Micronesia');
insert into countries (country) values ('Moldova');
insert into countries (country) values ('Monaco');
insert into countries (country) values ('Mongolia');
insert into countries (country) values ('Montserrat');
insert into countries (country) values ('Morocco');
insert into countries (country) values ('Mozambique');
insert into countries (country) values ('Myanmar');
insert into countries (country) values ('Namibia');
insert into countries (country) values ('Nauru');
insert into countries (country) values ('Nepal');
insert into countries (country) values ('Netherlands');
insert into countries (country) values ('New Caledonia');
insert into countries (country) values ('New Guinea');
insert into countries (country) values ('New Zealand');
insert into countries (country) values ('Nicaragua');
insert into countries (country) values ('Nigeria');
insert into countries (country) values ('Niue');
insert into countries (country) values ('Norfolk Island');
insert into countries (country) values ('Norway');
insert into countries (country) values ('Palau');
insert into countries (country) values ('Panama');
insert into countries (country) values ('Paraguay');
insert into countries (country) values ('Peru');
insert into countries (country) values ('Puerto');
insert into countries (country) values ('Philippines');
insert into countries (country) values ('Poland');
insert into countries (country) values ('Polynesia');
insert into countries (country) values ('Portugal');
insert into countries (country) values ('Romania');
insert into countries (country) values ('Russia');
insert into countries (country) values ('Rwanda');
insert into countries (country) values ('Saint Lucia');
insert into countries (country) values ('Samoa');
insert into countries (country) values ('San Marino');
insert into countries (country) values ('Senegal');
insert into countries (country) values ('Seychelles');
insert into countries (country) values ('Sierra Leone');
insert into countries (country) values ('Singapore');
insert into countries (country) values ('Slovakia');
insert into countries (country) values ('Slovenia');
insert into countries (country) values ('Somalia');
insert into countries (country) values ('South Africa');
insert into countries (country) values ('Spain');
insert into countries (country) values ('Sri Lanka');
insert into countries (country) values ('St. Helena');
insert into countries (country) values ('Sudan');
insert into countries (country) values ('Suriname');
insert into countries (country) values ('Swaziland');
insert into countries (country) values ('Sweden');
insert into countries (country) values ('Switzerland');
insert into countries (country) values ('Taiwan');
insert into countries (country) values ('Tajikistan');
insert into countries (country) values ('Tanzania');
insert into countries (country) values ('Thailand');
insert into countries (country) values ('Togo');
insert into countries (country) values ('Tokelau');
insert into countries (country) values ('Tonga');
insert into countries (country) values ('Trinidad');
insert into countries (country) values ('Tunisia');
insert into countries (country) values ('Turkey');
insert into countries (country) values ('Uganda');
insert into countries (country) values ('Ukraine');
insert into countries (country) values ('United Kingdom');
insert into countries (country) values ('United States');
insert into countries (country) values ('Uruguay');
insert into countries (country) values ('Uzbekistan');
insert into countries (country) values ('Vanuatu');
insert into countries (country) values ('Venezuela');
insert into countries (country) values ('Vietnam');
insert into countries (country) values ('Virgin Islands');
insert into countries (country) values ('Yugoslavia');
insert into countries (country) values ('Zaire');
insert into countries (country) values ('Zambia');
insert into countries (country) values ('Zimbabwe');